[package]
name = "tagged"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
failure = "0.1.5"
mokuroku = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10.1"
