[package]
name = "mokuroku"
version = "0.1.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
edition = "2018"
description = "Secondary indices like PouchDB for RocksDB in Rust."
repository = "https://github.com/nlfiedler/mokuroku"
readme = "README.md"
keywords = ["database", "index", "pouchdb", "rocksdb", "search"]
license = "Apache-2.0"
exclude = [
    "TODO.org",
    "test/*",
]

[dependencies]
failure = "0.1.5"
rocksdb = "0.12.3"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10.1"
